#!/usr/bin/env bash
set -euo pipefail
task_root="$(cd -- "$(dirname -- "$0")" && pwd)"
workspace_root="$(cd -- "$task_root/../.." && pwd)"
export CROSS_COMPILE="$workspace_root/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-elf/bin/aarch64-elf-"
export PATH="$workspace_root/toolchains/xpack-riscv-none-embed-gcc-8.3.0-2.3/bin:$workspace_root/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-elf/bin:$PATH"
cd "$task_root"
./fip/mk sc2_x4 --avb2 --testkey --fastboot-write > ../uboot-production-build.log 2>&1
# The vendor wrapper can continue packaging after a failed BL33 build.
if rg -q 'error:|make[^:]*: \*\*\*' ../uboot-production-build.log; then
    printf '%s\n' 'Build failed; inspect work/uboot-production-build.log.' >&2
    exit 1
fi
rg -q 'Bootloader build done!' ../uboot-production-build.log
rg -q '^#define CONFIG_FASTBOOT_WRITING_CMD' bl33/v2019/build/include/generated/version_autogenerated.h
python3 - <<'PY'
import hashlib
from pathlib import Path
tables = Path('bl33/v2019/board/amlogic/sc2_x4/firmware/stock-ddr-tables.bin').read_bytes()
assert hashlib.sha256(tables).hexdigest() == 'ba0ea5ff25ef9def071bf2e9377fe2f7c0c9a0229130adc1006bacf9904cf800'
for name in ('u-boot.bin.signed', 'u-boot.bin.usb.signed', 'u-boot.bin.sd.bin.signed'):
    path = Path('bl33/v2019/build') / name
    image = path.read_bytes()
    offset = 512 if '.sd.' in name else 0
    assert image[offset + 0x5d80:offset + 0x7910] == tables, name
    print(hashlib.sha256(image).hexdigest(), path)
PY
