#!/usr/bin/env bash
set -euo pipefail
task_root="$(cd -- "$(dirname -- "$0")/.." && pwd)"
workspace_root="${X4_WORKSPACE_ROOT:-$(cd -- "$task_root/../.." && pwd)}"
export CROSS_COMPILE="${CROSS_COMPILE:-$workspace_root/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-elf/bin/aarch64-elf-}"
riscv_bin="${RISCV_TOOLCHAIN_BIN:-$workspace_root/toolchains/xpack-riscv-none-embed-gcc-8.3.0-2.3/bin}"
export PATH="$riscv_bin:$(dirname -- "$CROSS_COMPILE"):$PATH"
cd "$task_root"
./fip/mk sc2_x4 --avb2 --testkey --fastboot-write > build-x4.log 2>&1
if rg -q 'error:|make[^:]*: \*\*\*' build-x4.log; then
    printf '%s\n' 'Build failed; inspect build-x4.log.' >&2
    exit 1
fi
rg -q 'Bootloader build done!' build-x4.log
rg -q '^#define CONFIG_FASTBOOT_WRITING_CMD' bl33/v2019/build/include/generated/version_autogenerated.h
